@startuml

actor "Fleet Manager" as FM
participant "<<System C4>>\nRobDroneGo" as RDG

activate FM

FM -> RDG: Requests to consult all robots
activate RDG
RDG -> RDG: Gets all robots
RDG --> FM: Shows all robots
deactivate RDG


@enduml
