@startuml
actor "Campus Manager" as user
participant "FrontEnd" as FE
participant "EditFloorHTML" as HTML
participant "EditFloorComponent" as COMP
participant "FloorService" as SERV
participant "FloorRoute" as ROUTE
participant "BuildingRoute" as ROUTE2
participant "BackEnd" as BE

activate user
user -> FE: asks to edit a floor
activate FE
FE -> HTML: /floor/edit
activate HTML
HTML -> COMP: ngOnInit()
activate COMP
COMP -> SERV: listBuildings()
activate SERV
SERV -> ROUTE2: GET /building/getAll
activate ROUTE2
ROUTE2 -> BE: getAllBuildings()
activate BE
BE --> ROUTE2: sends response with BuildingDTO's and http code 200
deactivate BE
ROUTE2 --> SERV: returns response with BuildingDTO's
deactivate ROUTE2
SERV --> COMP: returns response with BuildingDTO's
deactivate SERV
COMP --> HTML: returns response with BuildingDTO's
deactivate COMP
HTML --> FE: returns response with BuildingDTO's
deactivate HTML
FE --> user: shows list of building codes and asks to choose one
deactivate FE
user -> FE: chooses a building code
activate FE
FE -> HTML: inputs data
activate HTML
HTML -> COMP: onBuildingChange()
activate COMP
COMP -> COMP: loadFloorsByBuilding()
COMP -> SERV: listFloorsByBuilding()
activate SERV
SERV -> ROUTE: GET floor/getFloorsByBuildingId/:building_id
activate ROUTE
ROUTE -> BE: getFloorsByBuildingId()
activate BE
BE --> ROUTE: sends response with FloorDTO's and http code 200
deactivate BE
ROUTE --> SERV: returns response with FloorDTO's
deactivate ROUTE
SERV --> COMP: returns response with FloorDTO's
deactivate SERV
COMP --> HTML: returns response with FloorDTO's
deactivate COMP
HTML --> FE: returns response with FloorDTO's
deactivate HTML
FE --> user: shows list of floor names and asks to choose one
deactivate FE
user -> FE: chooses a floor
activate FE
FE -> HTML: inputs data
activate HTML
HTML -> COMP: editFloor()
activate COMP
COMP -> SERV: editFloor()
activate SERV
SERV -> ROUTE: PUT /floor//update/:domainId/(jsonBody)
activate ROUTE
ROUTE -> BE: updateFloor()
activate BE
BE --> ROUTE: sends response with FloorDTO and http code 200
deactivate BE
ROUTE --> SERV: returns response with FloorDTO and http code 200
deactivate ROUTE
SERV --> COMP: returns response with FloorDTO
deactivate SERV
COMP --> HTML: returns response with FloorDTO
deactivate COMP
HTML --> FE: returns response with FloorDTO
deactivate HTML
FE --> user: shows success message

@enduml