@startuml

actor "Campus Manager" as CM
participant "<<System C4>>\nRobDroneGo" as RDG

activate CM

CM -> RDG: Sends Elevator data
activate RDG
RDG -> RDG: Creates Elevator
RDG --> CM: Sends success/failure message
deactivate RDG


@enduml
