@startuml
participant "Campus Manager" as user
participant "Routing" as R
participant "EditElevatorComponent" as COMP
participant "ElevatorService" as SERVE
participant "BuildingService" as SERVB
participant "FloorService" as SERVF
participant "BackEnd" as BE
activate user
user -> R: Selects the elevator menu on the web app
activate R
R --> user: Shows the elevator menu
deactivate R
user -> R: Selects the edit elevator option
activate R
R --> user: Routes to the edit elevator component
R -> COMP: Requests the edit elevator component
deactivate R
activate COMP
COMP -> SERVB: Requests the list of buildings
activate SERVB
SERVB -> BE: Requests the list of buildings
activate BE
BE --> SERVB: Sends the list of buildings
deactivate BE
SERVB --> COMP: Sends the list of buildings
deactivate SERVB
COMP --> user: Shows the edit elevator component (html page) with the list of buildings for the user to select\nOnly one elevator per building can be created
deactivate COMP
user -> COMP: Selects the building (== select the elevator)
activate COMP
COMP -> SERVF: Requests the list of floors
activate SERVF
SERVF -> BE: Requests the list of floors
activate BE
BE --> SERVF: Sends the list of floors
deactivate BE
SERVF --> COMP: Sends the list of floors
deactivate SERVF
COMP --> user: Shows the list of floors for the user to select
deactivate COMP
user -> COMP: Selects multiple floors for the elevator to operate in\nand inputs new description
activate COMP
COMP -> SERVE: Requests the edition of the elevator
activate SERVE
SERVE -> BE: Requests the edition of the elevator
activate BE
BE --> SERVE: Sends the confirmation / failure of the edition of the elevator
deactivate BE
SERVE --> COMP: Sends the confirmation / failure of the edition of the elevator
deactivate SERVE
COMP --> user: Shows the confirmation / failure of the edition of the elevator
deactivate COMP
